version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinic
    ports:
      - "5433:5432"
    volumes:
      - clinic_data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/clinic
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

volumes:
  clinic_data:
